import type { CallContext } from "../auth/caller";
import * as identity from "./identity";
import * as gigs from "./gigs";
import * as orders from "./orders";
import * as credit from "./credit";
import * as cash from "./cash";
import * as payments from "./payments";
import * as payouts from "./payouts";
import * as remaining from "./remaining";
import * as config from "./config";
import * as reconciliation from "./reconciliation";
import * as scheduled from "./scheduled";
import * as webhooks from "./webhooks";

export type Handler = (ctx: CallContext) => Promise<unknown>;

export const handlers: Record<string, Handler> = {
  createSupplier: identity.createSupplier,
  convertBuyerToRole: identity.convertBuyerToRole,
  updateUserProfile: identity.updateUserProfile,
  disassociateMerchant: identity.disassociateMerchant,
  suspendUser: identity.suspendUser,
  restoreUser: identity.restoreUser,
  composeGig: gigs.composeGig,
  startGig: gigs.startGig,
  updateGigLocation: gigs.updateGigLocation,
  completeAndFinalizeGig: gigs.completeAndFinalizeGig,
  suspendGig: gigs.suspendGig,
  reassignGigDriver: gigs.reassignGigDriver,
  placeOrder: orders.placeOrder,
  cancelOrder: orders.cancelOrder,
  markOrderDelivered: orders.markOrderDelivered,
  placeMerchantOrder: orders.placeMerchantOrder,
  updateMerchantOrderStatus: orders.updateMerchantOrderStatus,
  cancelMerchantOrder: orders.cancelMerchantOrder,
  requestCreditIncrease: credit.requestCreditIncrease,
  setMerchantCreditLimit: credit.setMerchantCreditLimit,
  reviewCreditIncreaseRequest: credit.reviewCreditIncreaseRequest,
  setProvisionalCreditPolicy: credit.setProvisionalCreditPolicy,
  createPaymentIntent: payments.createPaymentIntent,
  processPayment: payments.processPayment,
  refundOrder: payments.refundOrder,
  issueCreditNote: payments.issueCreditNote,
  requestPayout: payouts.requestPayout,
  reviewPayoutRequest: payouts.reviewPayoutRequest,
  registerPayoutBeneficiary: payouts.registerPayoutBeneficiary,
  blockPayoutBeneficiary: payouts.blockPayoutBeneficiary,
  recordPayoutSettlement: payouts.recordPayoutSettlement,
  verifyManualPayout: payouts.verifyManualPayout,
  retryPayout: payouts.retryPayout,
  resendHandoverCode: cash.resendHandoverCode,
  issueOfflineCodeBatch: cash.issueOfflineCodeBatch,
  authorizeVerificationFallback: cash.authorizeVerificationFallback,
  initiateCreditRepayment: cash.initiateCreditRepayment,
  confirmCreditRepayment: cash.confirmCreditRepayment,
  getCashCustodySummary: cash.getCashCustodySummary,
  declareCashHandover: cash.declareCashHandover,
  confirmCashSettlement: cash.confirmCashSettlement,
  raiseCashDiscrepancy: cash.raiseCashDiscrepancy,
  resolveCashDiscrepancy: cash.resolveCashDiscrepancy,
  getFinancialReport: remaining.getFinancialReport,
  getFinanceReport: remaining.getFinanceReport,
  exportFinanceReport: remaining.exportFinanceReport,
  scheduleFinanceReport: remaining.scheduleFinanceReport,
  getEntitlements: remaining.getEntitlements,
  previewPlanChange: remaining.previewPlanChange,
  changeSubscriptionPlan: remaining.changeSubscriptionPlan,
  registerDeviceToken: remaining.registerDeviceToken,
  acknowledgeGig: remaining.acknowledgeGig,
  adjustProductStock: remaining.adjustProductStock,
  updateDriverPayRates: remaining.updateDriverPayRates,
  requestVerificationFallback: remaining.requestVerificationFallback,
  rejectVillageRequest: remaining.rejectVillageRequest,
  reassignOrderMerchant: remaining.reassignOrderMerchant,
  resumeOrderOnGig: remaining.resumeOrderOnGig,
  extendSubscriptionGrace: remaining.extendSubscriptionGrace,
  computeRouteMetrics: remaining.computeRouteMetrics,
  upsertRoute: remaining.upsertRoute,
  getSystemHealth: remaining.getSystemHealth,
  requestMyDataExport: remaining.requestMyDataExport,
  requestAccountDeletion: remaining.requestAccountDeletion,
  subscribeToPlan: remaining.subscribeToPlan,
  assignSubscription: remaining.assignSubscription,
  cancelSubscription: remaining.cancelSubscription,
  upsertCountry: config.upsertCountry,
  upsertState: config.upsertState,
  upsertDistrict: config.upsertDistrict,
  requestVillage: config.requestVillage,
  upsertVillage: config.upsertVillage,
  upsertSubscriptionPlan: config.upsertSubscriptionPlan,
  upsertPlanTariff: config.upsertPlanTariff,
  upsertSubscriptionOffer: config.upsertSubscriptionOffer,
  upsertOfferDiscountCode: config.upsertOfferDiscountCode,
  deactivateConfigurationRecord: config.deactivateConfigurationRecord,
  listConfigurationCatalog: config.listConfigurationCatalog,
  upsertTaxProfile: config.upsertTaxProfile,
  upsertTdsConfiguration: config.upsertTdsConfiguration,
  recordTdsChallan: config.recordTdsChallan,
  issueTdsCertificate: config.issueTdsCertificate,
  getTdsRegister: config.getTdsRegister,
  runReconciliation: reconciliation.runReconciliation,
  resolveReconciliationException: reconciliation.resolveReconciliationException,
  closeAccountingPeriod: reconciliation.closeAccountingPeriod,
  reopenAccountingPeriod: reconciliation.reopenAccountingPeriod,
  handleGatewayWebhook: webhooks.handleGatewayWebhook,
  postDueCreditRelief: async () => scheduled.postDueCreditRelief(),
};

export { payouts, scheduled };
